version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/:/etc/nginx/conf.d/
      - ./html/:/usr/share/nginx/html/
      - ./logs/:/var/log/nginx/
    networks:
      - myweb

networks:
  myweb:
    driver: bridge